dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: false

proxies:
  - name: 邪恶小鼠
    type: hysteria2
    server: 108.61.201.215
    port: 443
    password: OQ5Jl7zl7X3BMWpB_8xHXbwI
    skip-cert-verify: true
    sni: 108.61.201.215

  - name: 霸气小鼠
    type: ss
    server: 108.61.201.215
    port: 8388
    cipher: aes-128-gcm
    password: iat3j75fz4wfFNM6ZTu9FXWf
    udp: true

proxy-groups:
  - name: 自动切换
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 邪恶小鼠
      - 霸气小鼠

  - name: 节点选择
    type: select
    proxies:
      - 自动切换
      - 邪恶小鼠
      - 霸气小鼠
      - DIRECT

rules:
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,节点选择
