dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 8.8.8.8
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: false

proxies:
  - name: ss-node
    type: ss
    server: 108.61.201.215
    port: 8388
    cipher: aes-128-gcm
    password: iat3j75fz4wfFNM6ZTu9FXWf
    udp: true

proxy-groups:
  - name: GLOBAL
    type: select
    proxies:
      - DIRECT
      - ss-node

  - name: auto
    type: select
    proxies:
      - DIRECT
      - ss-node

rules:
  - MATCH,GLOBAL
